// ==UserScript==
// @name         Accoding Modern · 北航 OJ 管理界面
// @namespace    local.accoding.modern
// @version      1.2.0
// @description  本地界面美化、赛事统计看板与题面 Markdown 兼容编辑，保留原站登录和操作。
// @include      https://accoding.buaa.edu.cn:4000/*
// @run-at       document-end
// @grant        none
// @homepageURL  https://github.com/y38501148-max/accoding-modern
// @downloadURL  https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// @updateURL    https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// ==/UserScript==
// Generated by scripts/build.mjs. Edit src/ files, then run npm run build.

(() => {
'use strict';
if (location.origin !== 'https://accoding.buaa.edu.cn:4000') return;
function createContestCore() {
  const decode = value => {
    for (let i = 0; i < 2 && typeof value === 'string'; i++) value = JSON.parse(value);
    return value;
  };
  const time = value => {
    if (typeof value !== 'string' || !value.trim()) return NaN;
    // The API returns UTC ISO strings. Legacy timestamps use the site's Beijing timezone.
    const iso = /^\d{4}-\d\d-\d\d[ T]\d\d:\d\d:\d\d$/.test(value)
      ? value.replace(' ', 'T') + '+08:00' : value;
    return Date.parse(iso);
  };
  const letters = index => {
    let label = '';
    for (let n = index + 1; n > 0; n = Math.floor((n - 1) / 26)) label = String.fromCharCode(65 + (n - 1) % 26) + label;
    return label;
  };
  // Preserve the old site's rank-key convention, including its numbering after Z.
  const rankKey = index => {
    if (!index) return 'A';
    let value = '';
    while (index > 0) { value = String.fromCharCode(65 + index % 26) + value; index = Math.floor(index / 26); }
    return value;
  };
  function normalizeContest(raw) {
    const c = decode(raw);
    if (!c || !Array.isArray(c.problems)) throw new Error('赛事数据格式不匹配');
    const start = time(c.start_time), end = time(c.end_time);
    if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start) throw new Error('赛事起止时间无效');
    const seen = new Set();
    const problems = [...c.problems].sort((a,b) => Number(a.contest_problem_list?.order) - Number(b.contest_problem_list?.order)).map((p,index) => {
      if (!Number.isFinite(Number(p.contest_problem_list?.order)) || !/^\d+$/.test(String(p.id)) || seen.has(String(p.id))) throw new Error('题目序号或 ID 无效');
      seen.add(String(p.id));
      return { id: String(p.id), title: String(p.title || '未命名题目'), label: letters(index), rankKey: rankKey(index) };
    });
    return {id:String(c.id),title:String(c.title || '未命名赛事'),start,end,problems};
  }
  function aggregateRank(raw, problems) {
    const rows = decode(raw);
    if (!Array.isArray(rows)) throw new Error('排行榜数据格式不匹配');
    const result = problems.map(p => ({...p,accepted:0,total:0}));
    const keys = new Map(result.map(p => [p.rankKey,p]));
    for (const row of rows) {
      if (!row || !row.detail || typeof row.detail !== 'object' || Array.isArray(row.detail)) throw new Error('排行榜明细格式不匹配');
      for (const [key,detail] of Object.entries(row.detail)) {
        const p = keys.get(key);
        if (!p) continue;
        // A missing detail means no attempt; a pending result still represents an attempt.
        if (detail == null) continue;
        if (typeof detail !== 'object' || Array.isArray(detail) || (detail.result != null && typeof detail.result !== 'string')) throw new Error('排行榜结果格式不匹配');
        p.total++;
        if (detail.result === 'AC') p.accepted++;
      }
    }
    return result;
  }
  function phase(contest, now) {
    if (now < contest.start) return {key:'upcoming',text:'比赛未开始',caption:'距离开始',remaining:contest.start-now};
    if (now < contest.end) return {key:'running',text:'比赛进行中',caption:'距离结束',remaining:contest.end-now};
    return {key:'finished',text:'比赛已结束',caption:'Contest finished',remaining:0};
  }
  function duration(ms) {
    const seconds=Math.max(0,Math.ceil(ms/1000));
    return [Math.floor(seconds/3600),Math.floor(seconds/60)%60,seconds%60].map(n=>String(n).padStart(2,'0')).join(':');
  }
  function scale(rows) {
    const max = Math.max(1,...rows.map(r=>r.total));
    const unit = Math.pow(10,Math.floor(Math.log10(max)));
    return Math.ceil(max / unit) * unit;
  }
  return {decode,time,letters,normalizeContest,aggregateRank,phase,duration,scale};
}

function mountContestBoard(Core) {
  if (!/^\/contest(?:-ng)?\//.test(location.pathname) || document.getElementById('am-contest-tools')) return;
  const host=document.createElement('div'); host.id='am-contest-tools';
  const root=host.attachShadow({mode:'open'});
  const make=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls;if(text!==undefined)e.textContent=text;return e;};
  const btn=(text,fn)=>{const b=make('button','',text);b.type='button';b.addEventListener('click',fn);return b;};
  const style=make('style','');
  style.textContent=`
:host{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;color:#e6edf7;font-size:14px;line-height:1.5}
*{box-sizing:border-box}button,select{font:inherit}button{cursor:pointer;color:inherit;background:#1a2942;border:1px solid #34445f;padding:8px 13px;border-radius:8px}button:hover{background:#253a59}button:disabled{opacity:.5;cursor:wait}button:focus-visible,select:focus-visible{outline:2px solid #63a7ff;outline-offset:3px}
.launch{position:fixed;right:24px;bottom:24px;z-index:1040;background:#2458d3;color:#fff;border-color:#386ce4;padding:12px 19px;box-shadow:0 8px 26px #14264930}
.overlay{position:fixed;inset:0;z-index:2147483000;background:#0a1120;overflow:auto;padding:24px 32px;display:flex;flex-direction:column;gap:16px;height:100dvh;min-height:0}.overlay[hidden],.launch[hidden],[hidden]{display:none!important}.overlay:fullscreen{width:100%;height:100%;}
.head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.eyebrow{color:#8193b0;text-transform:uppercase;letter-spacing:2px;font-size:11px;margin-bottom:6px}h1{font-size:clamp(18px,2vw,30px);line-height:1.4;margin:0;font-weight:650;max-width:850px;overflow-wrap:anywhere}.actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;flex-shrink:0}.sub{color:#94a4be;margin-top:8px;font-size:12px}
.meta{display:flex;align-items:center;gap:22px;flex-wrap:wrap;color:#9aaac3;font-size:12px}.legend{display:flex;align-items:center;gap:8px}.dot{width:10px;height:10px;border-radius:3px;background:#50d6bc}.dot.total{background:#45606a;border:1px solid #719da9}.note{margin-left:auto}select{background:#14213a;color:#dce7f8;border:1px solid #34445f;border-radius:6px;padding:5px 8px}
.message{color:#ffce8a;background:#30251c;border:1px solid #69512c;padding:10px 15px;border-radius:8px;font-size:13px}.message:empty{display:none}.summary{display:flex;gap:25px;color:#8294b1;font-size:12px}.summary strong{font-variant-numeric:tabular-nums;color:#eef3fc;font-size:20px;margin-right:5px}
.chart-scroll{overflow:auto;position:relative;flex:1;min-height:220px}.chart{display:flex;position:relative;min-height:220px;height:100%;align-items:stretch;padding-top:32px}.column{position:relative;flex:1;min-width:78px;display:flex;flex-direction:column}.plot{position:relative;flex:1;min-height:70px;border-bottom:1px solid #7f8fa5;background:repeating-linear-gradient(to top,transparent 0,transparent calc(25% - 1px),#233049 calc(25% - 1px),#233049 25%)}
.bar{position:absolute;bottom:0;left:26%;width:53%;height:var(--height);background:var(--color);opacity:.21;border:1px solid var(--color);border-bottom:0;transition:height .5s ease}.bar.ac{left:12%;width:54%;opacity:1;background:linear-gradient(180deg,var(--color),color-mix(in srgb,var(--color),#000 16%));border:0;box-shadow:0 0 28px color-mix(in srgb,var(--color),transparent 90%)}
.delta{position:absolute;z-index:2;top:8px;left:0;right:0;text-align:center;color:#a2efbf;font-size:14px;font-weight:650;pointer-events:none;animation:am-rise 3s ease-out forwards}@keyframes am-rise{0%{opacity:0;transform:translateY(12px)}15%{opacity:1}75%{opacity:1}100%{opacity:0;transform:translateY(-18px)}}\n.value{position:absolute;bottom:calc(var(--height) + 7px);left:0;right:0;text-align:center;font-size:clamp(16px,2.2vw,36px);font-weight:650;color:var(--color);font-variant-numeric:tabular-nums;text-shadow:0 1px 9px #000;line-height:1.1;transition:bottom .5s ease}.numbers{text-align:center;border-right:1px solid #253149;padding:12px 5px;background:color-mix(in srgb,var(--color),#0a1120 94%);font-variant-numeric:tabular-nums}.label{font-size:30px;color:var(--color);font-weight:700}.accepted{color:#70e3af;font-size:21px;font-weight:650}.attempted{color:#f4cc75;font-size:18px}.problem-title{color:#8e9eba;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:130px;margin:7px auto 0;padding:0 6px}.no-data{margin:auto;text-align:center;padding:70px 20px;color:#8e9eba;font-size:17px}
.foot{border-top:1px solid #243147;padding-top:16px;display:flex;justify-content:space-between;align-items:center;gap:18px}.phase{font-size:clamp(24px,3vw,44px);letter-spacing:-.5px;color:#f2c96e;font-weight:650}.phase[data-phase=running]{color:#61dbb1}.phase[data-phase=upcoming]{color:#8bb8ff}.clock{text-align:right}.timer{font-size:clamp(24px,3vw,42px);font-variant-numeric:tabular-nums;letter-spacing:2px;color:#edf3fd}.clock small{color:#8c9cba}.privacy{font-size:11px;color:#7e91ae;margin:0}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}
.head,.meta,.summary,.foot,.privacy,.message{flex-shrink:0}
@media(max-width:700px){.overlay{padding:18px 14px;gap:14px}.head{flex-direction:column}.actions{gap:6px}.actions button{padding:7px 9px}.note{margin-left:0}.meta{gap:12px}.foot{align-items:flex-end}.summary{gap:15px}.launch{right:16px;bottom:16px}}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
`;
  root.append(style);
  const currentId=()=> location.pathname.match(/^\/contest\/(\d+)(?:\/|$)/)?.[1] || (/^\/contest-ng\//.test(location.pathname) ? location.hash.match(/^#\/(\d+)(?:\/|$)/)?.[1] : null);
  const launch=btn('▥ 赛事统计看板',()=>{const id=currentId();if(id)open(id);});launch.className='launch';
  const overlay=make('section','overlay');overlay.hidden=true;overlay.tabIndex=-1;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-label','赛事统计看板');
  const head=make('div','head'),titleArea=make('div','');
  const heading=make('h1','','赛事统计看板'),subtitle=make('div','sub');
  titleArea.append(make('div','eyebrow','ACCODING / CONTEST BOARD'),heading,subtitle);
  const actions=make('div','actions');
  const refreshButton=btn('立即刷新',()=>refresh());
  const pauseButton=btn('暂停刷新',()=>{paused=!paused;pauseButton.textContent=paused?'恢复刷新':'暂停刷新';schedule();if(!paused)refresh();updateNote();});
  const fullscreenButton=btn('全屏',async()=>{try{if(document.fullscreenElement===host || root.fullscreenElement===overlay)await document.exitFullscreen();else await overlay.requestFullscreen();}catch{message.textContent='浏览器暂不允许全屏；当前看板已铺满页面，可使用浏览器全屏功能。';}});
  const closeButton=btn('关闭 ×',()=>close());actions.append(refreshButton,pauseButton,fullscreenButton,closeButton);head.append(titleArea,actions);
  const meta=make('div','meta');
  for(const [cls,text] of [['','前柱：通过人数'],['total','后柱：尝试人数']]){const item=make('span','legend');item.append(make('i','dot '+cls),document.createTextNode(text));meta.append(item);}
  const intervalLabel=make('label','','刷新间隔 '),interval=make('select','');interval.setAttribute('aria-label','刷新间隔');
  for(const seconds of [15,30,60]){const option=make('option','',seconds+' 秒');option.value=String(seconds);interval.append(option);}interval.value='30';interval.addEventListener('change',()=>{schedule();updateNote();});intervalLabel.append(interval);meta.append(intervalLabel);
  const note=make('span','note');meta.append(note);
  const message=make('div','message');message.setAttribute('role','status');
  const summary=make('div','summary');
  const chartScroll=make('div','chart-scroll'),chart=make('div','chart');chart.setAttribute('role','img');chartScroll.append(chart);
  const foot=make('div','foot'),status=make('div','phase'),clockArea=make('div','clock'),caption=make('small',''),timer=make('div','timer');clockArea.append(caption,timer);foot.append(status,clockArea);
  const privacy=make('p','privacy','数据以当前账号可见的排行榜为准；同一人同一题只计一次。封榜、权限及榜单更新延迟可能影响统计。');
  overlay.append(head,meta,message,summary,chartScroll,foot,privacy);root.append(launch,overlay);document.body.append(host);
  let activeId=null,contest=null,data=null,clockOffset=0,clockSynced=false,lastSuccess=null,paused=false,poll=null,tick=null,controller=null,sequence=0,previousFocus=null,oldOverflow='',columns=[],chartSignature='',loadFailed=false;
  const formatDate=ms=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'medium',hour12:false}).format(new Date(ms));
  const updateNote=()=>{note.textContent=(paused?'已暂停':document.hidden?'后台暂停':`每 ${interval.value} 秒刷新`)+(lastSuccess?' · 更新于 '+new Date(lastSuccess).toLocaleTimeString('zh-CN',{hour12:false}):' · 尚未读取数据');};
  function updateClock(){
    updateNote();if(!contest){status.textContent=loadFailed?'数据暂不可用':'正在读取赛事';caption.textContent='';timer.textContent='—';return;}
    const p=Core.phase(contest,Date.now()+clockOffset);status.textContent=p.text;status.dataset.phase=p.key;
    caption.textContent=p.caption+(clockSynced?' · 服务器时间':' · 本机时间（未校准）');timer.textContent=p.key==='finished'?'':Core.duration(p.remaining);
  }
  function render(){
    heading.textContent=contest.title;subtitle.textContent=`比赛 #${activeId} · ${formatDate(contest.start)} — ${formatDate(contest.end)}（北京时间）`;
    summary.replaceChildren();for(const [value,label] of [[data.length,'道题'],[data.reduce((n,p)=>n+p.accepted,0),'人题通过'],[data.reduce((n,p)=>n+p.total,0),'人题尝试']]){const s=make('span','');s.append(make('strong','',String(value)),document.createTextNode(label));summary.append(s);}
    const signature=data.map(p=>p.id+':'+p.title).join('|');
    if(signature!==chartSignature || !columns.length){
      chart.replaceChildren();columns=[];chartSignature=signature;
      if(!data.length)chart.append(make('div','no-data','该赛事暂无可显示的题目'));
      const colors=['#ff657b','#ffa657','#e5d65c','#a3dd65','#55d898','#43d6c3','#4dc4ef','#719df7','#a68af4','#d180e4','#ee84b5'];
      for(let i=0;i<data.length;i++){
        const p=data[i],column=make('div','column');column.style.setProperty('--color',colors[i%colors.length]);
        const plot=make('div','plot'),total=make('div','bar'),ac=make('div','bar ac'),value=make('div','value');plot.append(total,ac,value);
        const numbers=make('div','numbers'),accepted=make('div','accepted'),attempted=make('div','attempted'),title=make('div','problem-title',p.title);title.title=p.title;
        numbers.append(make('div','label',p.label),accepted,attempted,title);column.append(plot,numbers);chart.append(column);columns.push({total,ac,value,accepted,attempted,column,plot,lastAccepted:null});
      }
    }
    const max=Core.scale(data);
    data.forEach((p,i)=>{const c=columns[i];
      c.plot.querySelector('.delta')?.remove();
      if(c.lastAccepted!==null && p.accepted>c.lastAccepted && !matchMedia('(prefers-reduced-motion: reduce)').matches){
        const delta=make('div','delta',`+${p.accepted-c.lastAccepted} 人通过`);
        delta.addEventListener('animationend',()=>delta.remove(),{once:true});c.plot.append(delta);
      }
      c.lastAccepted=p.accepted;
      c.total.style.setProperty('--height',p.total/max*88+'%');c.ac.style.setProperty('--height',p.accepted/max*88+'%');c.value.style.setProperty('--height',p.accepted/max*88+'%');c.value.textContent=p.accepted;c.accepted.textContent=p.accepted;c.attempted.textContent=p.total;c.column.title=`${p.label} · ${p.title}\n通过 ${p.accepted} 人 / 尝试 ${p.total} 人`;});
    chart.setAttribute('aria-label',data.map(p=>`${p.label}：通过 ${p.accepted} 人，尝试 ${p.total} 人`).join('；') || '暂无题目');updateClock();
  }
  async function read(path,signal){
    const response=await fetch(path,{credentials:'same-origin',cache:'no-store',signal});
    if(!response.ok)throw new Error(response.status===401||response.status===403?'无权读取，请检查原站登录及赛事权限':`服务返回 HTTP ${response.status}`);
    if(response.redirected || !response.headers.get('content-type')?.includes('json'))throw new Error('接口未返回 JSON，请检查登录状态');
    return response.json();
  }
  async function refresh(){
    if(!activeId || controller || document.hidden)return;
    const id=activeId,version=sequence;controller=new AbortController();const ownController=controller;
    const timeout=setTimeout(()=>ownController.abort(),15000);refreshButton.disabled=true;message.textContent='正在更新…';
    try{
      const [raw,rank,server]=await Promise.allSettled([read(`/api/contests/${id}`,controller.signal),read(`/api/contests/${id}/rank`,controller.signal),read('/api/contests/server_time',controller.signal)]);
      if(version!==sequence)return;
      if(raw.status==='rejected')throw raw.reason;
      const next=Core.normalizeContest(raw.value);if(next.id!==id)throw new Error('返回的赛事 ID 不匹配');
      contest=next;const remote=Core.time(server.value?.server_time);clockSynced=Number.isFinite(remote);clockOffset=clockSynced?remote-Date.now():0;
      heading.textContent=contest.title;subtitle.textContent=`比赛 #${id} · ${formatDate(contest.start)} — ${formatDate(contest.end)}（北京时间）`;updateClock();
      if(rank.status==='rejected')throw rank.reason;
      const stats=Core.aggregateRank(rank.value,next.problems);
      data=stats;lastSuccess=Date.now();loadFailed=false;
      message.textContent=clockSynced?'':'服务器时间暂不可用，倒计时暂按本机时间计算。';render();
    }catch(error){
      if(version!==sequence)return;
      loadFailed=true;
      message.textContent=(lastSuccess?'刷新失败，保留上次成功数据。':'未能读取统计数据。')+' '+(error.name==='AbortError'?'请求超时，请稍后重试。':error.message);
      if(!data){chart.replaceChildren(make('div','no-data','统计暂不可用 · 请检查登录或稍后刷新'));status.textContent='数据暂不可用';}
    }finally{clearTimeout(timeout);if(controller===ownController)controller=null;if(version===sequence){refreshButton.disabled=false;schedule();}}
  }
  function schedule(){clearTimeout(poll);poll=null;if(activeId&&!paused&&!document.hidden)poll=setTimeout(refresh,Number(interval.value)*1000);}
  function open(id){
    if(!/^\d+$/.test(id))return;
    if(activeId)close(false);
    previousFocus=document.activeElement;activeId=id;sequence++;paused=false;pauseButton.textContent='暂停刷新';contest=null;data=null;lastSuccess=null;columns=[];chartSignature='';loadFailed=false;
    oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';overlay.hidden=false;heading.textContent=`赛事 #${id}`;subtitle.textContent='';summary.replaceChildren();chart.replaceChildren(make('div','no-data','正在读取排行榜统计…'));overlay.focus();
    tick=setInterval(updateClock,1000);updateClock();refresh();
  }
  function close(restoreFocus=true){
    sequence++;activeId=null;controller?.abort();controller=null;clearTimeout(poll);clearInterval(tick);overlay.hidden=true;document.body.style.overflow=oldOverflow;
    if(document.fullscreenElement===host || root.fullscreenElement===overlay)document.exitFullscreen().catch(()=>{});
    if(restoreFocus)previousFocus?.focus();
  }
  root.addEventListener('keydown',event=>{
    if(overlay.hidden)return;
    if(event.key==='Escape'){event.preventDefault();close();}
    if(event.key==='Tab'){const focusable=[...overlay.querySelectorAll('button,select')].filter(e=>!e.disabled);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&(root.activeElement===first||root.activeElement===overlay)){event.preventDefault();last.focus();}else if(!event.shiftKey&&root.activeElement===last){event.preventDefault();first.focus();}}
  });
  document.addEventListener('visibilitychange',()=>{schedule();if(!document.hidden&&activeId&&!paused)refresh();updateNote();});
  const route=()=>{launch.hidden=!currentId();};window.addEventListener('hashchange',route);route();
  // Links are discovered from the actual page; never enumerate inaccessible contest IDs.
  const addListButtons=()=>{
    if(currentId())return;
    for(const a of document.querySelectorAll('a[href]')){
      if(a.dataset.amBoardLink || a.closest('#navbar'))continue;
      const url=new URL(a.href,location.href);if(url.origin!==location.origin)continue;
      const id=url.pathname==='/contest-ng/index.html'?url.hash.match(/^#\/(\d+)\/?$/)?.[1]:url.pathname.match(/^\/contest\/(\d+)\/index\/?$/)?.[1];
      if(!id || currentId())continue;
      a.dataset.amBoardLink='1';const b=document.createElement('button');b.type='button';b.textContent='统计看板';b.className='am-button';b.style.cssText='margin-left:10px;font-size:12px;white-space:nowrap';b.addEventListener('click',event=>{event.preventDefault();open(id);});a.after(b);
    }
  };
  addListButtons();
  const observer=new MutationObserver(()=>{addListButtons();route();});observer.observe(document.body,{childList:true,subtree:true});
}

mountContestBoard(createContestCore());
// The contest Angular app replaces its ng-view on hash navigation and has no #page/#navbar.
// Scope styles to its stable template selectors so late ng-include and route changes work.
(() => {
  if (!/^\/contest-ng\//.test(location.pathname) || document.getElementById('am-ng-style')) return;
  let disabled=false;
  try { disabled=sessionStorage.getItem('am-disabled')==='1'; } catch (_) {}
  const toggle=value=>{try{sessionStorage.setItem('am-disabled',value?'1':'0');}catch(_){}location.reload();};
  const control=document.createElement('button');control.type='button';
  if(disabled){
    control.textContent='启用新版界面';
    control.style.cssText='position:fixed;bottom:24px;left:24px;z-index:1040;padding:10px 16px;border:0;border-radius:8px;background:#2458d3;color:#fff;cursor:pointer';
    control.addEventListener('click',()=>toggle(false));document.body.append(control);return;
  }
  const style=document.createElement('style');style.id='am-ng-style';
  style.textContent=`
html.am-ng{--ng-bg:#f5f7fb;--ng-card:#fff;--ng-line:#e3e9f2;--ng-ink:#202b40;--ng-muted:#6b7a90;--ng-blue:#2458d3;--ng-soft:#edf3ff;background:var(--ng-bg)}
.am-ng body{background:var(--ng-bg)!important;background-image:none!important;color:var(--ng-ink);font:14px/1.7 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif}
.am-ng body>.container-fluid{padding:0 28px 80px;max-width:1920px;margin:auto}
.am-ng body>.container-fluid>.row,.am-ng body>.container-fluid>.row>div{margin:0;padding:0;width:100%;float:none}
.am-ng [ng-view]{display:grid;grid-template-columns:238px minmax(0,1fr);gap:26px;margin:0!important;align-items:start}
.am-ng [ng-view]:before,.am-ng [ng-view]:after{display:none}
.am-ng [ng-view]>nav{grid-column:1/-1;position:sticky;top:0;z-index:1030;min-height:76px;margin:0 -28px;padding:12px 28px;border:0;border-bottom:1px solid var(--ng-line);border-radius:0;background:#fff;box-shadow:none}
.am-ng [ng-view]>nav .navbar-brand{font-size:0;display:flex;align-items:center;gap:9px;margin-right:16px}
.am-ng [ng-view]>nav .navbar-brand:before{content:'a/';display:inline-grid;place-items:center;width:32px;height:32px;background:var(--ng-blue);border-radius:9px;color:white;font:700 17px monospace}
.am-ng [ng-view]>nav .navbar-brand:after{content:'accoding';font-size:23px;font-weight:750;letter-spacing:-1px;color:var(--ng-ink)}
.am-ng .navbar-default .navbar-nav>li>a{padding:14px 12px;font-size:13px;color:#65738a;text-shadow:none;border-radius:7px;background:transparent;box-shadow:none}
.am-ng .navbar-default .navbar-nav>li>a:hover{background:#f6f8fc;color:var(--ng-blue)}
.am-ng .navbar-default .navbar-nav>.active>a{background:var(--ng-soft)!important;color:var(--ng-blue)!important;font-weight:650}
.am-ng .navbar-right{font-size:12px}.am-ng .am-ng-reset{font:inherit;font-size:12px;margin:9px 6px;padding:5px 9px;border:1px solid var(--ng-line);border-radius:7px;background:#fff;color:var(--ng-muted);cursor:pointer}
.am-ng [ng-view]>.col-lg-2{position:sticky;top:101px;width:auto;float:none;padding:0;min-width:0;max-height:calc(100vh - 125px);overflow:auto}
.am-ng [ng-view]>.col-lg-2>h4{font-size:18px;line-height:1.65;font-weight:650;margin:0 4px 20px;overflow-wrap:anywhere}
.am-ng [ng-view]>.col-lg-2>.form-horizontal{padding:9px;background:#fff;border:1px solid var(--ng-line);border-radius:12px}
.am-ng [ng-view]>.col-lg-2>.form-horizontal>.list-group-item{border:0!important;border-radius:7px;margin:3px 0;padding:11px 14px;background:transparent;color:#5f6e84;font-size:14px}
.am-ng [ng-view]>.col-lg-2>.form-horizontal>.list-group-item.active{background:var(--ng-soft)!important;color:var(--ng-blue)!important;font-weight:650;text-shadow:none}
.am-ng [ng-include="'detail/time.html'"]{margin-top:18px;border:1px solid var(--ng-line);border-radius:12px;overflow:hidden;background:#fff}
.am-ng [ng-include="'detail/time.html'"]>label{float:none!important;display:block;width:100%;margin:0!important;padding:13px 10px!important;background:#fff!important;border:0!important;border-bottom:1px solid #edf0f6!important;font-size:11px;font-weight:400;color:var(--ng-muted)}
.am-ng [ng-include="'detail/time.html'"]>label:last-child{border-bottom:0!important;background:#f8faff!important}
.am-ng [ng-include="'detail/time.html'"] label label{font-size:13px;font-weight:550;color:#344660;font-variant-numeric:tabular-nums;margin-bottom:0}
.am-ng [ng-include="'detail/time.html'"]>label:last-child>label:last-of-type{font-size:19px;letter-spacing:1px;color:var(--ng-blue)}
.am-ng [ng-view]>.col-lg-10{width:auto;float:none;min-width:0;padding:28px 30px;background:#fff;border:1px solid var(--ng-line);border-radius:13px;min-height:calc(100vh - 140px);overflow-wrap:anywhere}
.am-ng [ng-view]>.col-lg-10>div:first-child:has(>h4){display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:25px}
.am-ng h1,.am-ng h2,.am-ng h3,.am-ng h4{color:var(--ng-ink);font-weight:650;line-height:1.5;letter-spacing:-.4px}
.am-ng h1{font-size:28px}.am-ng h2{font-size:23px}.am-ng h3{font-size:23px;margin-top:0}.am-ng h4{font-size:22px;margin:0}
.am-ng h3 small{display:inline-block;font-size:11px;letter-spacing:0;color:var(--ng-muted);font-weight:400}
.am-ng a{color:var(--ng-blue)}.am-ng a[ng-click]{cursor:pointer}
.am-ng .markdown-body{font-size:15px;line-height:1.95;color:#334057;overflow-wrap:anywhere}
.am-ng .markdown-body h2{border-bottom:1px solid var(--ng-line);padding-bottom:10px;margin:28px 0 16px}
.am-ng .markdown-body li>p{margin:7px 0}.am-ng .markdown-body strong{color:#273d61}
.am-ng .markdown-body pre{padding:16px;border:1px solid var(--ng-line);border-radius:8px;background:#f6f8fc;color:#34465f;white-space:pre;overflow:auto}
.am-ng code{color:#36598d;background:#edf3fb;border-radius:4px;font-size:.9em}.am-ng pre code{background:transparent;color:inherit}
.am-ng .markdown-body blockquote{border-left:3px solid #b5caf4;background:#f7faff;color:#68778b;padding:12px 18px}
.am-ng .problem-title{margin:25px 0 12px;font-size:28px;color:var(--ng-ink)}.am-ng .problem-limit,.am-ng .problem-limit+p{color:var(--ng-muted);font-size:12px}
.am-ng .btn{border-radius:7px;padding:8px 14px;font-size:13px;background-image:none!important;text-shadow:none;box-shadow:none!important;white-space:nowrap}
.am-ng .btn-primary{background:var(--ng-blue);border-color:var(--ng-blue);color:#fff}.am-ng .btn-primary:hover{background:#1945b0}
.am-ng .btn-default{background:#fff;border-color:#dfe6f0;color:#53637a}.am-ng .btn-default.active{background:var(--ng-soft);border-color:#aec6f6;color:var(--ng-blue)}
.am-ng .btn-success{background:#e9f7f1;border-color:#c4e8d7;color:#167452}.am-ng .btn-danger{background:#fff0f3;border-color:#f4cbd2;color:#b73951}
.am-ng a[ng-repeat="problem in Contest.data.problems"]{margin:0 4px 7px 0;min-width:38px}
.am-ng .form-control{height:auto;min-height:36px;padding:7px 10px;border:1px solid #dce3ed;border-radius:7px;box-shadow:none;color:var(--ng-ink);background:#fff;font-size:13px}
.am-ng .form-control:focus{border-color:#8daff0;box-shadow:0 0 0 3px #edf3ff}.am-ng textarea.form-control{line-height:1.8;resize:vertical}
.am-ng .form-control[disabled]{background:#f7f9fc;color:#596981}
.am-ng .list-group-item{background:#fff;border-color:var(--ng-line);color:#5b6b82}.am-ng .list-group-item.active{background:var(--ng-soft)!important;color:var(--ng-blue)!important;border-color:#c8d8f6;text-shadow:none}
.am-ng .am-ng-table-wrap{position:relative;overflow:auto;max-width:100%;border:1px solid var(--ng-line);border-radius:10px;margin:18px 0}
.am-ng .am-ng-table-wrap>table{display:table!important;margin:0!important;border:0!important;width:100%;background:#fff;font-size:13px}
.am-ng table thead input.form-control{min-width:120px}.am-ng table thead select.form-control{min-width:90px}
.am-ng table>thead>tr>td,.am-ng table>thead>tr>th{padding:12px!important;border:0!important;border-bottom:1px solid var(--ng-line)!important;background:#f7f9fc!important;color:var(--ng-muted);font-size:12px;font-weight:550;vertical-align:middle}
.am-ng table>tbody>tr>td{padding:12px!important;border:0!important;border-bottom:1px solid #edf0f5!important;background:#fff;color:#34425a;vertical-align:middle}
.am-ng table>tbody>tr:last-child>td{border-bottom:0!important}.am-ng table.table-hover>tbody>tr:hover>td{background:#f8faff}
.am-ng table>tbody>tr>td.success{background:#edf8f1;color:#24794e}.am-ng table>tbody>tr>td.danger{background:#fdf0f2;color:#b14a5c}.am-ng table>tbody>tr>td.warning{background:#fff7e9;color:#986b20}.am-ng table>tbody>tr>td.info{background:#eaf3ff;color:#2464ae}
.am-ng .red-td{color:#b84d61}.am-ng .green-td{color:#a07526}.am-ng .blue-td{color:#188063}
.am-ng .pagination>li>a{border-color:var(--ng-line);color:#536b91;font-size:12px}.am-ng .pagination>.active>a{background:var(--ng-blue);border-color:var(--ng-blue);color:#fff}
.am-ng .popover,.am-ng .modal-content{border:1px solid var(--ng-line);border-radius:10px;box-shadow:0 12px 40px #1c34551c}
.am-ng :focus-visible{outline:2px solid #497ce0;outline-offset:3px}
@media(max-width:1200px){.am-ng body>.container-fluid{padding:0 20px 80px}.am-ng [ng-view]{grid-template-columns:210px minmax(0,1fr);gap:20px}.am-ng [ng-view]>nav{margin:0 -20px;padding:10px 20px}.am-ng [ng-view]>nav .navbar-brand{margin-right:0}.am-ng .navbar-default .navbar-nav>li>a{padding:14px 8px}.am-ng [ng-view]>.col-lg-10{padding:22px}}
@media(max-width:1000px){.am-ng [ng-view]>nav .navbar-brand:after{font-size:0}.am-ng [ng-view]>nav .navbar-brand{padding-right:4px}.am-ng .am-ng-reset{font-size:11px;padding:5px}}
@media(max-width:767px){.am-ng body>.container-fluid{padding:0 14px 80px}.am-ng [ng-view]{display:block}.am-ng [ng-view]>nav{position:relative;margin:0 -14px 18px;padding:9px 14px}.am-ng [ng-view]>nav .navbar-brand:after{font-size:23px}.am-ng [ng-view]>.col-lg-2{position:static;max-height:none;margin-bottom:20px}.am-ng [ng-view]>.col-lg-2>h4{font-size:18px;margin-bottom:12px}.am-ng [ng-view]>.col-lg-2>.form-horizontal{display:flex;overflow:auto;gap:4px;padding:5px}.am-ng [ng-view]>.col-lg-2>.form-horizontal>.list-group-item{white-space:nowrap;flex-shrink:0;padding:8px 12px}.am-ng [ng-include="'detail/time.html'"]{display:flex;margin-top:12px}.am-ng [ng-include="'detail/time.html'"]>label{flex:1;min-width:0;padding:10px 5px!important}.am-ng [ng-include="'detail/time.html'"] label label{font-size:11px}.am-ng [ng-include="'detail/time.html'"]>label:last-child>label:last-of-type{font-size:14px}.am-ng [ng-view]>.col-lg-10{padding:20px 16px;min-height:0}.am-ng h1,.am-ng .problem-title{font-size:23px}.am-ng .markdown-body{font-size:14px}.am-ng h3{font-size:21px}}
@media print{.am-ng nav,.am-ng [ng-view]>.col-lg-2{display:none!important}.am-ng [ng-view]{display:block}.am-ng [ng-view]>.col-lg-10{border:0}.am-ng .am-ng-table-wrap{overflow:visible}}
`;
  document.head.append(style);document.documentElement.classList.add('am-ng');
  control.textContent='恢复原版外观';control.className='am-ng-reset';control.addEventListener('click',()=>toggle(true));
  const enhance=()=>{
    const nav=document.querySelector('[ng-view]>nav .navbar-middle');
    if(nav&&!control.isConnected){const li=document.createElement('li');li.append(control);nav.append(li);}
    // Keep original table nodes and all Angular bindings; only add a scroll container.
    for(const table of document.querySelectorAll('[ng-view]>.col-lg-10 table')){
      if(table.closest('.am-ng-table-wrap,.modal,.popover')||table.parentElement.closest('table'))continue;
      const wrap=document.createElement('div');wrap.className='am-ng-table-wrap';table.before(wrap);wrap.append(table);
    }
  };
  let pending=false;
  const observer=new MutationObserver(()=>{if(!pending){pending=true;requestAnimationFrame(()=>{pending=false;enhance();});}});
  observer.observe(document.body,{childList:true,subtree:true});enhance();
})();

(() => {
  'use strict';
  if (location.origin !== 'https://accoding.buaa.edu.cn:4000' || document.getElementById('am-style')) return;
  const page = document.querySelector('#page');
  const navbar = document.querySelector('#navbar');
  if (!page || !navbar) return;
  const el = (tag, cls, text) => {
    const node = document.createElement(tag);
    node.className = cls;
    if (text !== undefined) node.textContent = text;
    return node;
  };
  const button = (text, handler) => {
    const node = el('button', 'am-button', text);
    node.type = 'button';
    node.addEventListener('click', handler);
    return node;
  };
  let disabled = false;
  try { disabled = sessionStorage.getItem('am-disabled') === '1'; } catch (_) {}
  const setDisabled = value => {
    try { sessionStorage.setItem('am-disabled', value ? '1' : '0'); } catch (_) {}
    location.reload();
  };
  if (disabled) {
    const restore = button('启用新版界面', () => setDisabled(false));
    restore.style.cssText = 'position:fixed;bottom:20px;right:20px;z-index:9999;padding:12px 20px;background:#2458d3;color:white;border:0;border-radius:10px;cursor:pointer';
    document.body.append(restore);
    return;
  }
  const style = el('style', '');
  style.id = 'am-style';
  style.textContent = `
html.am { --am-bg:#f5f7fb; --am-card:#fff; --am-line:#e5eaf1; --am-ink:#202b40; --am-muted:#69778e; --am-blue:#2458d3; --am-soft:#edf3ff; }
html.am body {background:var(--am-bg)!important;color:var(--am-ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;font-size:14px;line-height:1.65;}
.am #container {width:auto!important;margin:0 0 0 232px;padding:0 36px;}
.am #container>.row {margin:0;}
.am #container>.row>div:first-child:empty {display:none;}
.am #container>.row>.col-lg-10 {width:100%;float:none;padding:0;}
.am #navbar {position:fixed;inset:0 auto 0 0;width:232px;min-height:100vh;margin:0;padding:30px 16px;border:0;border-right:1px solid var(--am-line);border-radius:0;background:#fff;box-shadow:none;z-index:1030;overflow-y:auto;}
.am #navbar .container-fluid {padding:0;}
.am #navbar .navbar-header,.am #navbar .navbar-nav,.am #navbar .navbar-nav>li {float:none!important;}
.am #navbar .navbar-brand {float:none;display:block;height:auto;margin:0;padding:0 12px 32px;font-size:0;color:var(--am-ink);font-weight:750;}
.am #navbar .navbar-brand::before {content:'a/';display:inline-grid;place-items:center;background:var(--am-blue);color:white;width:36px;height:36px;margin-right:10px;border-radius:10px;font:700 18px monospace;white-space:nowrap;vertical-align:middle;}
.am #navbar .navbar-brand::after {content:'accoding';font-size:23px;letter-spacing:-1px;vertical-align:middle;}
.am #navbar .navbar-collapse {display:block!important;visibility:visible!important;height:auto!important;padding:0;border:0;box-shadow:none;}
.am #navbar .navbar-toggle {display:none;}
.am #navbar .navbar-nav {margin:0!important;}
.am #navbar .navbar-middle::before {content:'教学工作空间';display:block;padding:0 14px 14px;font-size:11px;font-weight:600;letter-spacing:2px;color:var(--am-muted);}
.am #navbar .navbar-nav>li {margin:5px 0;}
.am #navbar .navbar-nav>li>a {display:flex;gap:13px;align-items:center;margin:0;padding:12px 14px!important;border-radius:9px;background:transparent;color:#59677c!important;font-size:14px;line-height:23px;text-decoration:none;}
.am #navbar .navbar-middle>li>a::before {content:'◇';width:20px;text-align:center;font-size:19px;color:#8a97ab;}
.am #navbar #problempage::before {content:'▤';}.am #navbar #contestpage::before {content:'⚑';}.am #navbar #submissionpage::before {content:'≡';}.am #navbar #informationpage::before {content:'○';}
.am #navbar .navbar-nav>li>a:hover {background:#f5f7fb;}
.am #navbar .navbar-nav>li>a.nav-change {color:var(--am-blue)!important;background:var(--am-soft)!important;font-weight:650;}
.am #navbar .navbar-right {margin-top:40px!important;padding-top:20px;border-top:1px solid var(--am-line);}
.am #navbar .navbar-right a {font-size:12px!important;}
.am #page {margin:0;min-height:calc(100vh - 160px)!important;}
.am #page>div {min-width:0;}
.am #page>div.col-lg-12 {padding:0;}
.am-topbar {display:flex;justify-content:space-between;align-items:center;gap:16px;min-height:82px;border-bottom:1px solid var(--am-line);margin-bottom:30px;color:var(--am-muted);font-size:12px;}
.am-topbar strong {font-weight:550;color:var(--am-ink);}
.am-top-actions {display:flex;gap:10px;align-items:center;}
.am-tag {color:#168063;font-size:11px;background:#eaf7f0;border-radius:6px;padding:4px 9px;white-space:nowrap;}
.am-button {border:1px solid var(--am-line);background:white;border-radius:8px;padding:7px 12px;color:#536178;font:inherit;cursor:pointer;}
.am-button:hover {border-color:#adc1ee;color:var(--am-blue);}
.am a {color:var(--am-blue);}
.am #page h1,.am #page h2,.am #page h3 {color:var(--am-ink);font-weight:650;letter-spacing:-.5px;line-height:1.45;}
.am #page h1 {font-size:30px;}.am #page h2 {font-size:23px;}.am #page h3 {font-size:25px;margin:0 0 22px;}
.am #page .am-list-table {border:0!important;margin:0;background:white;min-width:780px;}
.am-table-wrap {position:relative;overflow-x:auto;border:1px solid var(--am-line);border-radius:12px;background:white;margin:0 0 22px;}
.am #page .am-list-table>tbody>tr>td,.am #page .am-list-table>thead>tr>th {padding:15px 16px!important;border:0;border-bottom:1px solid #edf0f5;background:white!important;color:var(--am-ink);text-align:left;vertical-align:middle;font-size:13px;line-height:1.6;}
.am #page .am-list-table>tbody>tr:hover>td {background:#f8faff!important;}
.am #page .am-list-table>tbody>tr.am-table-heading>td,.am #page .am-list-table>thead>tr>th {background:#f9fafc!important;color:var(--am-muted);font-size:11px;font-weight:600;white-space:nowrap;padding-top:13px!important;padding-bottom:13px!important;}
.am #page .am-list-table tr:last-child>td {border-bottom:0;}
.am #page .am-list-table tr.am-filtered {display:none!important;}
.am #page .am-list-table td a {text-decoration:none;}
.am #page .am-list-table td a:hover {text-decoration:underline;}
.am #page .am-list-table td.progress {min-width:86px;border-radius:0;box-shadow:none;height:auto;}
.am #page .am-list-table td.progress .progress-bar {height:6px;min-width:4px;margin:5px 0;border-radius:6px;background-image:none;box-shadow:none;animation:none;}
.am .progress-bar-success {background:#479b84;}.am .progress-bar-warning {background:#dc9b38;}.am .progress-bar-danger {background:#d66070;}
.am #page .am-list-table td.bluetd {color:#167a55!important;font-weight:600;}.am #page .am-list-table td.redtd {color:#bd495e!important;font-weight:600;}.am #page .am-list-table td.greentd {color:#996b1d!important;font-weight:600;}
.am-toolbar {display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;margin:0 0 16px;}
.am-search {display:flex;align-items:center;gap:10px;padding:9px 13px;background:white;border:1px solid var(--am-line);border-radius:9px;color:var(--am-muted);font-size:13px;}
.am-search input {border:0!important;outline:0;background:transparent;box-shadow:none!important;width:250px;max-width:55vw;font:inherit;color:var(--am-ink);}
.am-search:focus-within {border-color:#8daff0;box-shadow:0 0 0 3px #edf3ff;}
.am-count {color:var(--am-muted);font-size:12px;}
.am-empty {padding:35px;text-align:center;color:var(--am-muted);}
.am .form-control {height:auto;min-height:38px;padding:8px 12px;border:1px solid #dce3ed;border-radius:8px;box-shadow:none;background:white;color:var(--am-ink);}
.am .form-control:focus {border-color:#8daff0;box-shadow:0 0 0 3px #edf3ff;}
.am textarea.form-control {line-height:1.7;font-family:ui-monospace,SFMono-Regular,Consolas,"PingFang SC",monospace;}
.am #page textarea.markdown-body {background:#182337!important;color:#e1e8f4!important;border:1px solid #293750!important;font-family:ui-monospace,SFMono-Regular,Consolas,"PingFang SC",monospace;font-size:14px;line-height:1.85;padding:22px!important;}
.am #page .button {display:inline-block;width:auto!important;height:auto!important;min-height:36px;max-width:100%;padding:8px 14px!important;border-radius:7px;font-size:13px!important;line-height:1.6;white-space:nowrap;background-image:none!important;box-shadow:none!important;text-shadow:none!important;}
.am .btn-info {background:#eaf2ff;border-color:#c9dbf8;color:#2458d3;}
.am .btn {background-image:none!important;box-shadow:none!important;text-shadow:none!important;border-radius:7px;padding:8px 15px;font-size:13px;transition:background .15s;}
.am .btn-primary,.am .btn-success {background:var(--am-blue);border-color:var(--am-blue);color:white;}
.am .btn-primary:hover,.am .btn-success:hover {background:#1945b0;border-color:#1945b0;}
.am .btn-danger {background:#fff0f2;border-color:#f4cbd2;color:#b73951;}
.am .btn-warning {background:#fff6e7;border-color:#f0d3a0;color:#896018;}
.am .btn-default {background:white;border-color:var(--am-line);color:#58667c;}
.am .list-group-item {padding:12px 15px;background:white!important;border-color:var(--am-line);color:#59677c!important;}
.am .list-group-item.change-color,.am .list-group-item.active {background:var(--am-soft)!important;color:var(--am-blue)!important;border-color:#d6e2ff;}
.am .markdown-body {background:white;border:1px solid var(--am-line);border-radius:12px;padding:30px!important;font-size:15px;line-height:1.9;}
.am .markdown-body h2 {margin-top:30px;border-bottom:1px solid var(--am-line);padding-bottom:10px;}
.am .markdown-body pre {background:#f6f8fb;border:1px solid var(--am-line);border-radius:8px;padding:16px;color:#35415a;}
.am .markdown-body blockquote {border-left:3px solid #b5caf4;color:#68778b;background:#f7faff;padding:12px 18px;}
.am .problem-limit {color:var(--am-muted);font-size:12px;}
.am .modal-content {border:1px solid var(--am-line);border-radius:14px;box-shadow:0 20px 80px #15244030;}
.am .modal-header,.am .modal-footer {border-color:var(--am-line);padding:20px;}.am .modal-body {padding:22px;}
.am .panel {border:1px solid var(--am-line);border-radius:10px;box-shadow:none;}.am .panel-heading {background:#f9fafc!important;background-image:none!important;border-color:var(--am-line);}
.am #container footer,.am #container .footer {color:var(--am-muted);font-size:11px;}
.am .am-home {display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:26px 0 40px;}
.am-home a {display:block;background:white;border:1px solid var(--am-line);padding:25px;border-radius:12px;text-decoration:none!important;transition:border-color .15s,transform .15s;}
.am-home a:hover {border-color:#abc2f3;transform:translateY(-2px);}
.am-home strong {display:block;color:var(--am-ink);font-size:18px;margin-bottom:8px;}
.am-home span {color:var(--am-muted);font-size:13px;}
.am :focus-visible {outline:2px solid #497ce0;outline-offset:3px;}
.am-dense #page .am-list-table>tbody>tr:not(.am-table-heading)>td {padding-top:8px!important;padding-bottom:8px!important;}
@media(min-width:1000px){.am #page.am-problem-layout {display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:22px;}.am #page.am-problem-layout:before,.am #page.am-problem-layout:after {display:none;}.am #page.am-problem-layout>div {width:auto;float:none;padding:0;}.am #page.am-problem-layout>div.am-blank-aside {display:none;}}
@media(min-width:1600px){.am #container {padding-left:52px;padding-right:52px;}}
@media(max-width:1000px){.am #container {margin-left:190px;padding:0 20px;}.am #navbar {width:190px;padding:24px 10px;}.am #navbar .navbar-brand::after {font-size:20px;}.am #navbar .navbar-brand {padding-left:5px;}}
@media(max-width:700px){.am #container {margin:0;padding:0 16px;}.am #navbar {position:relative;width:100%;min-height:0;border:0;border-bottom:1px solid var(--am-line);padding:16px;margin-bottom:0;}.am #navbar .navbar-brand {padding:0 0 12px;}.am #navbar .navbar-middle {display:flex;overflow-x:auto;gap:3px;}.am #navbar .navbar-middle::before,.am #navbar .navbar-middle>li>a::before {display:none;}.am #navbar .navbar-middle>li {flex-shrink:0;margin:0;}.am #navbar .navbar-nav>li>a {padding:8px 10px!important;}.am #navbar .navbar-right {display:flex;justify-content:space-between;margin-top:10px!important;padding-top:8px;}.am-topbar {min-height:70px;margin-bottom:22px;}.am-top-actions .am-tag {display:none;}.am #page h3 {font-size:23px;}.am .am-home {grid-template-columns:1fr;}.am .markdown-body {padding:20px!important;}.am #page>div {padding-left:0;padding-right:0;}}
@media(prefers-reduced-motion:reduce){.am * {transition:none!important;animation:none!important;}}
@media print{.am #navbar,.am-topbar,.am-toolbar {display:none!important;}.am #container {margin:0;padding:0;}.am-table-wrap {overflow:visible;}.am #page .am-list-table {min-width:0;}}
`;
  document.head.append(style);
  document.documentElement.classList.add('am');
  navbar.querySelector('.navbar-brand')?.setAttribute('aria-label', 'Accoding 管理站首页');
  const topbar = el('header', 'am-topbar');
  const breadcrumb = el('div', '', '工作空间 / ');
  const selected = navbar.querySelector('.nav-change');
  breadcrumb.append(el('strong', '', selected?.textContent.trim() || '概览'));
  const actions = el('div', 'am-top-actions');
  actions.append(el('span', 'am-tag', '本地外观 · 原站服务'), button('恢复原版', () => setDisabled(true)));
  topbar.append(breadcrumb, actions);
  page.before(topbar);

  // Enhance list pages only; never replace rows, IDs, controls, forms, or handlers.
  const isList = /^\/(problem|contest|group|submission)\/index\/?$/.test(location.pathname);
  if (isList) for (const table of page.querySelectorAll('table.table')) {
    if (table.closest('.modal')) continue;
    table.classList.add('am-list-table');
    const rows = [...table.rows].filter(row => row.cells.length);
    const heading = rows[0];
    if (!heading) continue;
    heading.classList.add('am-table-heading');
    const dataRows = rows.slice(1);
    const wrap = el('div', 'am-table-wrap');
    table.before(wrap);
    wrap.append(table);
    const toolbar = el('div', 'am-toolbar');
    const label = el('label', 'am-search');
    label.append(el('span', '', '⌕'));
    const input = el('input', '');
    input.type = 'search';
    input.placeholder = '筛选当前页：名称、ID、作者…';
    input.setAttribute('aria-label', '筛选当前页记录');
    label.append(input);
    const info = el('span', 'am-count');
    info.setAttribute('aria-live', 'polite');
    const compact = button('紧凑行高', () => {
      const dense = document.documentElement.classList.toggle('am-dense');
      compact.textContent = dense ? '舒适行高' : '紧凑行高';
      compact.setAttribute('aria-pressed', String(dense));
    });
    compact.setAttribute('aria-pressed', 'false');
    toolbar.append(label, info, compact);
    wrap.before(toolbar);
    const empty = el('div', 'am-empty', '当前页没有匹配的记录，请调整关键词或切换原站分页。');
    empty.hidden = true;
    wrap.append(empty);
    const filter = () => {
      const query = input.value.trim().toLocaleLowerCase();
      let count = 0;
      for (const row of dataRows) {
        const matches = [...row.cells].map(cell => cell.textContent).join(' ').toLocaleLowerCase().includes(query);
        row.classList.toggle('am-filtered', !matches);
        if (matches) count++;
      }
      info.textContent = query ? `当前页 ${count} / ${dataRows.length} 条` : `当前页 ${dataRows.length} 条 · 可用下方分页查看更多`;
      empty.hidden = count !== 0;
    };
    input.addEventListener('input', filter);
    // Some original list tables sit inside a POST form. Local search must not submit it.
    input.addEventListener('keydown', event => {
      if (event.key === 'Enter') { event.preventDefault(); event.stopPropagation(); }
    });
    filter();
  }

  const directColumns = [...page.children].filter(n => n.tagName === 'DIV');
  if (directColumns.length === 3 && directColumns[1].querySelector('.markdown-body')) {
    const first = directColumns[0];
    if (!first.textContent.trim() && !first.querySelector('input,button,a,img,iframe')) {
      first.classList.add('am-blank-aside');
      page.classList.add('am-problem-layout');
    }
  }
  if (location.pathname === '/') {
    const dashboard = el('section', 'am-home');
    for (const [path, title, description] of [
      ['/problem/index', '题目管理', '查看题面、编辑内容、管理测试数据'],
      ['/contest/index', '赛事管理', '组织上机赛事，查看比赛配置'],
      ['/submission/index', '评测记录', '查看提交结果与运行详情'],
      ['/group/index', '教学小组', '进入小组，管理课程与成员']
    ]) {
      const link = el('a', '');
      link.href = path;
      link.append(el('strong', '', title + ' ↗'), el('span', '', description));
      dashboard.append(link);
    }
    const heading = page.querySelector('h1,h2,h3');
    if (heading) heading.after(dashboard); else page.prepend(dashboard);
  }
})();

// Both OJ's escaped subscripts and ordinary TeX represent subscripts here.
function createMarkdownCore() {
  const escaped = (s, i) => {
    let n = 0;
    while (i > 0 && s[--i] === '\\') n++;
    return n % 2 === 1;
  };
  function mathBody(s, mode) {
    return s.replace(/\\*_/g, run => {
      const n = run.length - 1;
      return mode === 'oj' ? (n % 2 ? run : '\\' + run) : (n % 2 ? run.slice(1) : run);
    });
  }
  function convert(source, mode = 'oj') {
    const eol = source.includes('\r\n') ? '\r\n' : '\n';
    const s = source.replace(/\r\n/g, '\n');
    let out = '', i = 0;
    while (i < s.length) {
      const startLine = i === 0 || s[i - 1] === '\n';
      if (startLine) {
        const end = s.indexOf('\n', i), stop = end < 0 ? s.length : end;
        const line = s.slice(i, stop);
        const fence = line.match(/^ {0,3}(`{3,}|~{3,})(.*)$/);
        if (fence && !(fence[1][0] === '`' && fence[2].includes('`'))) {
          const rest = s.slice(end < 0 ? s.length : end + 1);
          const closing = new RegExp('^ {0,3}' + fence[1][0] + '{' + fence[1].length + ',}[ \\t]*(?:\\n|$)', 'm').exec(rest);
          // An unfinished fence is a code block through EOF, as in CommonMark.
          const content = rest.slice(0, closing ? closing.index : rest.length);
          const consumed = (end < 0 ? s.length : end + 1) + (closing ? closing.index + closing[0].length : rest.length);
          if (mode === 'oj') {
            if (out && !out.endsWith('\n\n')) out += out.endsWith('\n') ? '\n' : '\n\n';
            const lines = content.split('\n');
            if (content.endsWith('\n')) lines.pop();
            out += lines.map(line => '    ' + line).join('\n');
            // Keep following prose out of the indented code block.
            if (consumed < s.length) out += '\n\n';
            else if (s.endsWith('\n')) out += '\n';
          } else out += s.slice(i, consumed);
          i = consumed;
          continue;
        }
        // Existing code blocks are already portable; never touch their whitespace or TeX.
        if (/^( {4}|\t)/.test(line)) {
          out += s.slice(i, end < 0 ? s.length : end + 1);
          i = end < 0 ? s.length : end + 1;
          continue;
        }
      }
      // Raw HTML code and tag attributes, URL destinations and inline code are not math.
      const raw = s.slice(i).match(/^<(pre|code|script|style|textarea)\b[^>]*>[\s\S]*?<\/\1\s*>/i);
      if (raw) { out += raw[0]; i += raw[0].length; continue; }
      const tag = s[i] === '<' && s.slice(i).match(/^<[^>\n]+>/);
      if (tag) { out += tag[0]; i += tag[0].length; continue; }
      const url = s.slice(i).match(/^https?:\/\/[^\s<>]+/);
      if (url) { out += url[0]; i += url[0].length; continue; }
      if (s[i] === '`' && !escaped(s, i)) {
        const run = s.slice(i).match(/^`+/)[0];
        let j = i + run.length, close = -1;
        while ((j = s.indexOf(run, j)) >= 0) {
          if (s[j - 1] !== '`' && s[j + run.length] !== '`') { close = j; break; }
          j += run.length;
        }
        if (close >= 0) { const end = close + run.length; out += s.slice(i, end); i = end; continue; }
        out += run; i += run.length; continue;
      }
      const delim = !escaped(s, i) && (s.startsWith('\\[', i) ? ['\\[', '\\]', '$$'] : s.startsWith('\\(', i) ? ['\\(', '\\)', '$'] : s.startsWith('$$', i) ? ['$$', '$$', '$$'] : s[i] === '$' && /\S/.test(s[i + 1] || '') ? ['$', '$', '$'] : null);
      if (delim) {
        const [open, close, target] = delim;
        let j = i + open.length, found = -1;
        while ((j = s.indexOf(close, j)) >= 0) {
          if (!escaped(s, j) && (close !== '$' || (s[j - 1] !== '$' && s[j + 1] !== '$' && /\S/.test(s[j - 1])))) { found = j; break; }
          j += close.length;
        }
        if (found >= 0) {
          const body = s.slice(i + open.length, found);
          // Do not interpret separate paragraphs, code fences or inline code as a single formula.
          if (!/\n\s*\n|`/.test(body) && !(target === '$' && body.includes('\n'))) {
            out += target + mathBody(body, mode) + target;
            i = found + close.length;
            continue;
          }
        }
      }
      out += s[i++];
    }
    return eol === '\n' ? out : out.replace(/\n/g, eol);
  }
  return { toOJ: source => convert(source, 'oj'), toCommon: source => convert(source, 'common') };
}

function mountMarkdownEditor(Core) {
  const input = document.querySelector('textarea#problem-description[name="description"]');
  const preview = document.getElementById('preview');
  if (!input?.form || !preview || document.getElementById('am-markdown-tools')) return;
  const form = input.form;
  const toolbar = document.createElement('div');
  toolbar.id = 'am-markdown-tools';
  toolbar.innerHTML = `<div class="am-md-actions"><strong>Markdown 兼容编辑</strong><button type="button" data-copy="common">复制通用 Markdown</button><button type="button" data-copy="oj">复制 OJ 格式</button><button type="button" data-show>查看保存格式</button></div><p>支持普通／转义下标、两种公式定界符及围栏代码。保存时自动适配 OJ，编辑原文保持不变。</p><span role="status" aria-live="polite"></span><details><summary>将保存的题面源码</summary><textarea readonly aria-label="将保存的题面源码" spellcheck="false"></textarea></details>`;
  const style = document.createElement('style');
  style.textContent = `#am-markdown-tools{margin:12px 0;padding:14px 16px;border:1px solid #dbe5ef;background:#f5f8fc;border-radius:10px;color:#344258;font:13px/1.6 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif}#am-markdown-tools .am-md-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}#am-markdown-tools strong{margin-right:auto}#am-markdown-tools button{border:1px solid #cbd7e6;background:#fff;color:#315787;border-radius:6px;padding:6px 10px;cursor:pointer;font:inherit}#am-markdown-tools p{margin:8px 0 0}#am-markdown-tools [role=status]{color:#386749}#am-markdown-tools details:not([open]){display:none}#am-markdown-tools details{margin-top:10px}#am-markdown-tools textarea{display:block;width:100%!important;min-height:220px;font:13px/1.65 ui-monospace,monospace;white-space:pre;overflow:auto;padding:12px;border:1px solid #cbd7e6;border-radius:6px;background:white;color:#243249}#am-markdown-tools button:focus-visible{outline:2px solid #377ce2;outline-offset:2px}`;
  document.head.append(style);
  const editRow = input.closest('.problem-edit-left')?.parentElement;
  (editRow || input).before(toolbar);
  const status = toolbar.querySelector('[role=status]');
  const details = toolbar.querySelector('details');
  const saved = details.querySelector('textarea');
  const setSaved = value => { saved.value = value; saved.setAttribute('_value', value); };
  const updateSaved = () => { if (details.open) setSaved(Core.toOJ(input.value)); };
  toolbar.querySelector('[data-show]').addEventListener('click', () => { details.open = !details.open; updateSaved(); });
  for (const button of toolbar.querySelectorAll('[data-copy]')) {
    button.addEventListener('click', async () => {
      const value = button.dataset.copy === 'oj' ? Core.toOJ(input.value) : Core.toCommon(input.value);
      try {
        await navigator.clipboard.writeText(value);
        status.textContent = button.dataset.copy === 'oj' ? '已复制 OJ 格式。' : '已复制通用 Markdown。';
      } catch {
        details.open = true; setSaved(value); saved.focus(); saved.select();
        status.textContent = '浏览器未允许剪贴板写入，已选中源码，可按 Ctrl/Cmd+C 复制。';
      }
    });
  }
  // FormData runs for native submission, jQuery .submit(), and new FormData(form).
  // It changes only the outgoing description, so cancelled confirmation keeps the draft intact.
  form.addEventListener('formdata', event => {
    if (!input.disabled && input.form === form && event.formData.has(input.name)) {
      event.formData.set(input.name, Core.toOJ(input.value));
    }
  });
  function render() {
    if (!window.markdown?.toHTML) return;
    preview.innerHTML = window.markdown.toHTML(Core.toOJ(input.value), 'Maruku');
    window.MathJax?.Hub?.Queue(['Typeset', window.MathJax.Hub, preview]);
    updateSaved();
  }
  // Preserve the site's other editors and oninput handler; only this description uses conversion.
  const original = window.Editor;
  if (typeof original === 'function') {
    window.Editor = function(inputId, previewId) {
      if (inputId !== input.id || previewId !== preview.id) return original.apply(this, arguments);
      input.editor = { update: render };
      render();
    };
  } else input.addEventListener('input', render);
  input.addEventListener('input', updateSaved);
  form.addEventListener('reset', () => setTimeout(render, 0));
  render();
}

mountMarkdownEditor(createMarkdownCore());
})();
