import test from 'node:test';
import assert from 'node:assert/strict';
import {createContestCore} from '../src/contest-core.mjs';
const C=createContestCore(),problems=[{id:'9',rankKey:'A',label:'A'}];
const row=(id,result,wrong_count=0)=>({user:{id},detail:{A:{result,wrong_count}}});
const snap=rows=>C.rankSnapshot(rows,problems);
test('first snapshot is a baseline, not a replay of historic submissions',()=>{const next=snap([row(1,'AC',4)]);assert.deepEqual(C.rankEvents(null,next),{reset:true,events:[]});});
test('fresh failure then AC grows attempt column once and accepted column once',()=>{const changes=C.rankEvents(snap([]),snap([row(1,'AC',1)]));assert.deepEqual(changes.events.map(e=>[e.kind,e.accepted,e.total]),[['failed',0,1],['accepted',1,0]]);});
test('repeat failures animate minus without increasing attempted people',()=>{const changes=C.rankEvents(snap([row(1,'WA',0)]),snap([row(1,'WA',2)]));assert.equal(changes.events.length,2);assert.ok(changes.events.every(e=>e.kind==='failed'&&!e.total&&!e.accepted));});
test('pending creates attempt with no fake failure; later verdict resolves once',()=>{const pending=snap([row(1,null)]);assert.deepEqual(C.rankEvents(snap([]),pending).events.map(e=>e.kind),['attempt']);assert.deepEqual(C.rankEvents(pending,snap([row(1,'WA')])).events.map(e=>[e.kind,e.total]),[['failed',0]]);});
test('user identity, not rank row position, determines events',()=>{const old=snap([row(1,'WA'),row(2,'AC')]);const next=snap([row(2,'AC'),row(1,'AC',1)]);assert.deepEqual(C.rankEvents(old,next).events.map(e=>[e.kind,e.total]),[['accepted',0]]);assert.equal(C.rankEvents(next,next).events.length,0);});
test('corrections and missing identities synchronize instead of inventing negative events',()=>{assert.equal(C.rankEvents(snap([row(1,'AC')]),snap([row(1,'WA')])).reset,true);assert.equal(C.rankEvents(snap([row(1,'WA',3)]),snap([row(1,'WA',1)])).reset,true);assert.equal(C.rankEvents(snap([row(1,'AC')]),snap([])).reset,true);const incomplete=snap([{detail:{A:{result:'AC'}}}]);assert.equal(incomplete.stats[0].accepted,1);assert.equal(incomplete.reliable,false);assert.equal(C.rankEvents(snap([]),incomplete).reset,true);});
test('every replay step preserves accepted <= attempted and converges to latest rank',()=>{const before=snap([row(1,'WA'),row(2,'AC')]),after=snap([row(1,'AC',2),row(2,'AC'),row(3,'AC'),row(4,'WA',2),row(5,null)]);let a=before.stats[0].accepted,t=before.stats[0].total;for(const e of C.rankEvents(before,after).events){a+=e.accepted;t+=e.total;assert.ok(a<=t);assert.ok(t/C.scale([{total:t}])*88<=88);}assert.equal(a,after.stats[0].accepted);assert.equal(t,after.stats[0].total);});
test('random slots stay ordered within a bounded playback window, including 1s refresh',()=>{for(const interval of [1000,2000,5000,60000]){const events=C.unitBursts(30,interval,()=>.5);assert.equal(events.length,30);assert.ok(events[0].delay>0);assert.ok(events.at(-1).delay<=Math.min(15000,interval));assert.ok(events.every((e,i)=>e.left>=18&&e.left<=82&&(i===0||e.delay>events[i-1].delay)));}});

test('direct acceptance emits only +1, never a failure symbol',()=>{const events=C.rankEvents(snap([]),snap([row(1,'AC')])).events;assert.deepEqual(events.map(e=>C.unitSymbol(e.kind)),['+1']);assert.deepEqual(events.map(e=>[e.accepted,e.total]),[[1,1]]);});
test('pending, judging and unknown neutral events never produce a minus',()=>{for(const result of [null,undefined,'PD','WJ','Judging']){const events=C.rankEvents(snap([]),snap([row(1,result)])).events;assert.deepEqual(events.map(e=>C.unitSymbol(e.kind)),['']);}assert.equal(C.unitSymbol('unexpected'),'');});
test('a pending submission resolved as AC emits +1 without increasing attempts again',()=>{const events=C.rankEvents(snap([row(1,null)]),snap([row(1,'AC')])).events;assert.deepEqual(events.map(e=>[C.unitSymbol(e.kind),e.total]),[['+1',0]]);});
test('a newly confirmed WA produces exactly one minus, not a plus',()=>{const events=C.rankEvents(snap([]),snap([row(1,'WA')])).events;assert.deepEqual(events.map(e=>C.unitSymbol(e.kind)),['-']);});
