import { readFile, writeFile } from 'node:fs/promises';
const root=new URL('../',import.meta.url);
const theme=(await readFile(new URL('src/theme.js',root),'utf8')).replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/, '');
const core=(await readFile(new URL('src/contest-core.mjs',root),'utf8')).replace(/^export /gm,'');
const ui=await readFile(new URL('src/contest-board.js',root),'utf8');
const contestTheme=await readFile(new URL('src/contest-theme.js',root),'utf8');
const header=`// ==UserScript==
// @name         Accoding Modern · 北航 OJ 管理界面
// @namespace    local.accoding.modern
// @version      1.1.1
// @description  本地界面美化与赛事统计投屏看板，保留原站登录和操作。
// @include      https://accoding.buaa.edu.cn:4000/*
// @run-at       document-end
// @grant        none
// @homepageURL  https://github.com/y38501148-max/accoding-modern
// @downloadURL  https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// @updateURL    https://raw.githubusercontent.com/y38501148-max/accoding-modern/main/accoding-modern.user.js
// ==/UserScript==
// Generated by scripts/build.mjs. Edit src/ files, then run npm run build.

`;
await writeFile(new URL('accoding-modern.user.js',root),header+`(() => {\n'use strict';\nif (location.origin !== 'https://accoding.buaa.edu.cn:4000') return;\n${core}\n${ui}\nmountContestBoard(createContestCore());\n${contestTheme}\n${theme}\n})();\n`);
